# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='vote_down',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='vote_up',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
