# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20171129_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vote_down',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vote_up',
        ),
    ]
