# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20171129_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
