# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_auto_20171207_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='instagram.Review'),
        ),
    ]
