# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_profile_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='followers',
        ),
    ]
